name: storeub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.5+1
  firebase_core: ^2.24.2
  http: ^1.1.0
  foundation: ^0.0.5
  location: ^8.0.1
  geocoding: ^4.0.0
  firebase_auth: ^4.16.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/